spring:
  application:
    name: gateway
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    server1:  /server1/**
    server2:  /server2/**
